name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Ejecuta el pipeline en cada push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Configura la versión de Python

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt --target lambda_layer/python

    - name: Zip dependencies
      run: |
        cd lambda_layer
        zip -r ../lambda_layer.zip .

    - name: Zip lambda_function.py
      run: |
        cd src
        zip -r ../lambda_function.zip lambda_function.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

